#!/bin/bash

BRANCH=$(git rev-parse --abbrev-ref HEAD)

rm -rf target
rm -rf resources/public/js/compiled
git branch -D gh-pages
git checkout -b gh-pages
lein cljsbuild once dev
lein cljsbuild once devcards
rm -rf dev
rm -rf src
rm -rf target
rm -rf .gitignore
rm -rf .rebel_readline_history
rm -rf deploy
rm -rf figwheel_server.log
rm -rf project.clj
rm -rf README.md
rm -rf shell.nix

mv resources/public/* .
git add .
git commit -m "deploy"
git push -f origin gh-pages

git checkout $BRANCH